Feature/delete update get handlers
qst-project/backend pull request #10
Opened 2022-04-11 15:05 UTC by skinnykaen

2022-04-11 15:10 UTC, vladtrc requested changes
пожалуйста не нужно мёрджить перед закрытием всех комментов как в прошлый раз!

2022-04-11 15:10 UTC, vladtrc commented on pkg/api/questionnaire.go
> +		ref, err = s.QuestionnaireUseCase.Invoke(qst)
не понял...

2022-04-11 15:10 UTC, vladtrc commented on pkg/api/questionnaire.go
> +	//qst, err := s.QuestionnaireUseCase.GetQuestionnaire(ref)
ошибка? это точно работает?

2022-04-11 15:10 UTC, vladtrc commented on test/grpc_test.go
> +	//resp, err := client.CreateQuestionnaire(ctx, &api.CreateQuestionnaireRequest{Questionnaire: &questionnaire})
надо всё же дописать
важно:
1. создать эти данные в БД ПЕРЕД тестом
2. научиться удалять все данные из используемых таблиц перед запуском очередного файла

2022-04-11 15:21 UTC, skinnykaen commented on test/grpc_test.go
> +	//resp, err := client.CreateQuestionnaire(ctx, &api.CreateQuestionnaireRequest{Questionnaire: &questionnaire})
Ты думаешь что я не понимаю этого ....

2022-04-12 20:56 UTC, vladtrc commented
![image](https://user-images.githubusercontent.com/25867395/163053189-06025dfe-5a09-458d-a81f-51b21eb4c7b7.png)
надо ещё юзать енамы

2022-04-13 10:03 UTC, vladtrc commented on test/unit/mappingDbToCore_test.go
> +	if dbQuestionnaire.Ref != coreQuestionnaire.Ref {
assertEquals?

2022-04-13 10:05 UTC, vladtrc commented on test/unit/mappingDbToCore_test.go
> +	coreQuestion := &core.Question{
надо создавать тестовые объекты из factory 
questionnaireFactory.Create()
либо сейчас там шаблоны есть, мб можно что-то вроде factory.Create<Questionaire>(), но первый вариант предпочтительнее кмк

2022-04-13 10:07 UTC, vladtrc commented on test/unit/mappingProtoToCore_test.go
> +package unit
тесты на маппинг конечно это сильно... но вообще нужно ли это тестировать?))

2022-04-13 10:08 UTC, vladtrc commented on test/unit/mappingProtoToCore_test.go
> +package unit
давай пообщаемся

2022-04-13 10:08 UTC, vladtrc commented on test/grpc_test.go
> +func TestGetQuestionnaireEndpoint(t *testing.T) {
вообще в grpc это не называется endpoint, это procedure - или я ошибаюсь?

2022-04-13 10:09 UTC, vladtrc commented on test/grpc_test.go
> +		Ref:   "/testRef",
давай не будем хранить "/ " в рефе

2022-04-13 10:20 UTC, vladtrc commented on pkg/api/delegate.go
> -func Setup(createQuestionnaireUseCase usecase.CreateQuestionnaireUseCase) Module {
надо вынести delegate в отдельную папку
кстати pkg, если не ошибаюсь, мы тоже не поназначению используем

2022-04-18 19:06 UTC, skinnykaen commented on test/unit/mappingDbToCore_test.go
> +	if dbQuestionnaire.Ref != coreQuestionnaire.Ref {
сделано

2022-04-18 19:07 UTC, skinnykaen commented on test/unit/mappingDbToCore_test.go
> +	coreQuestion := &core.Question{
сделал папку templates c готовыми модельками

2022-04-18 19:07 UTC, skinnykaen commented on test/unit/mappingProtoToCore_test.go
> +package unit
Да, мне нужны. Это важный функционал. Мне так легче его дебажить если что-то меняется

2022-04-18 19:08 UTC, skinnykaen commented on test/grpc_test.go
> +func TestGetQuestionnaireEndpoint(t *testing.T) {
Не знаю. Если метод не в потоке вроде Unary называется

2022-04-18 19:08 UTC, skinnykaen commented on test/grpc_test.go
> +		Ref:   "/testRef",
ок

2022-04-18 19:08 UTC, skinnykaen commented on pkg/api/delegate.go
> -func Setup(createQuestionnaireUseCase usecase.CreateQuestionnaireUseCase) Module {
вынес

2022-04-18 19:09 UTC, skinnykaen commented
> ![image](https://user-images.githubusercontent.com/25867395/163053189-06025dfe-5a09-458d-a81f-51b21eb4c7b7.png) надо ещё юзать енамы

сделал

2022-04-18 19:09 UTC, skinnykaen commented on pkg/api/questionnaire.go
> +	protoQuestionnaire.FromCore(&qst)
сделано

2022-04-18 19:10 UTC, vladtrc commented on test/unit/mappingProtoToCore_test.go
> +package unit
> Member

а если выполнять go test, выполнятся и интеграционные и unit? тобишь все эти тоже прогоняются каждый раз?

2022-04-18 19:12 UTC, vladtrc commented on test/unit/mappingDbToCore_test.go
> +	if dbQuestionnaire.Ref != coreQuestionnaire.Ref {
можешь проверить, вызовется ли паника в случае если разные вернутся? например assertEquals(0, 1) - если тесты останавливаются и пишется ошибка то всё ок и резолви трэд

2022-04-18 19:14 UTC, skinnykaen commented on test/unit/mappingDbToCore_test.go
> +	if dbQuestionnaire.Ref != coreQuestionnaire.Ref {
все хорошо, закрываю

2022-04-18 19:14 UTC, skinnykaen commented on test/unit/mappingProtoToCore_test.go
> +package unit
нет, только unit

2022-04-18 19:46 UTC, vladtrc approved these changes

2022-04-18 19:46 UTC, merged